### ISSUE TITLE
[SUGESTÃO] - Implementação de GitHub Action para Detecção Gamificada de Issues Duplicadas

### ISSUE THREAD

**Issue by AnjosBeatriz** [digitalinnovationone/dio-lab-open-source#46047]
**Sua sugestão está relacionada a um problema? Por favor descreva.**
Não.

**Descreva a solução que você gostaria**

### 1. Objetivo Geral

O principal objetivo desse GitHub Action é verificar se uma nova issue é duplicada antes de ser criada. Além disso, o Action implementa um sistema de gamificação que incentiva os contribuidores a seguirem boas práticas ao criar issues, recompensando-os com pontos e feedback positivo.

#### Arquivo de Configuração
O arquivo de configuração do GitHub Action será colocado em `.github/workflows/check-duplicate-issues.yml` e contém as definições necessárias para o workflow.

#### Detalhes do Código

```yaml
name: Check for Duplicate Issues with Gamification

on:
  issues:
    types: [opened]  # Aciona o workflow ao abrir uma nova issue

jobs:
  check-duplicates:
    runs-on: ubuntu-latest  # Executa em um ambiente Linux
    steps:
      - name: Find Duplicates
        uses: actions/find-duplicates@v1.0.0
        with:
          searchField: 'title,body'  # Verifica duplicatas no título e corpo da issue
          exclude: 'Enhancement'
          searchWithin: 'open'  # Pesquisa apenas nas issues abertas
          searchType: 'similar'  # Busca por similaridade

      - name: Process Issue
        id: process
        run: |
          if [ "${{ steps.find-duplicates.outputs.duplicate_found }}" == "true" ]; then
            echo "Duplicate issue found! Please check the existing issues."
            echo "score=0" >> $GITHUB_ENV  # Pontuação é 0 para issues duplicadas
            echo "message=Consider searching for existing issues before creating a new one." >> $GITHUB_ENV
          else
            echo "No duplicate found. Great job!"
            echo "score=10" >> $GITHUB_ENV  # Pontuação é 10 para issues únicas
            echo "message=Thank you for contributing a unique issue!" >> $GITHUB_ENV
          fi

      - name: Add Comments
        run: |
          gh pr comment ${{ github.event.issue.number }} --body "${{ env.message }}"
          
      - name: Update Score
        run: |
          echo "Your score for this action is: ${{ env.score }}"
```

#### A. Acionamento do Workflow
- O workflow é acionado sempre que uma nova issue é aberta no repositório. Isso garante que todas as novas contribuições sejam analisadas.

#### B. Verificação de Duplicatas
- **Find Duplicates**: O primeiro passo utiliza a ação `find-duplicates` para verificar se já existe uma issue com o mesmo título ou corpo. A pesquisa é feita apenas nas issues abertas, e se uma duplicata for encontrada, a variável `duplicate_found` será definida como `true`.

#### C. Processamento da Issue
- **Pontuação**:
  - Se uma duplicata for encontrada, a pontuação do usuário é definida como 0, e uma mensagem é gerada para incentivá-lo a pesquisar antes de criar novas issues.
  - Se não houver duplicatas, a pontuação é de 10 pontos, e o usuário é elogiado por sua contribuição única.
- As mensagens são armazenadas em variáveis de ambiente para uso posterior.

#### D. Comentários Automáticos
- O passo "Add Comments" utiliza a CLI do GitHub para adicionar um comentário à issue. O comentário inclui o feedback sobre a duplicação e a pontuação, ajudando o usuário a entender o que fez certo ou errado.

#### E. Atualização de Pontuação
- Por fim, a pontuação é exibida, o que fornece feedback imediato ao usuário sobre sua contribuição. Isso pode ser expandido para armazenar as pontuações em um sistema de banco de dados para rastreamento de desempenho ao longo do tempo.

#### A. Níveis de Contribuição
- A pontuação acumulada ao longo do tempo pode ser utilizada para definir níveis de contribuição (por exemplo, Iniciante, Explorador, Mestre Contribuidor).

#### B. Badges e Recompensas
- Usuários que atingem certas pontuações podem receber badges visuais, que podem ser exibidos ao lado das issues ou em seus perfis, motivando-os a contribuir de maneira mais significativa.

#### C. Feedback Visual
- A comunicação de resultados (como pontuação e mensagens de incentivo) ajuda a criar uma experiência positiva, encorajando a repetição de comportamentos desejados.

### 5. Conclusão

Esse GitHub Action combina a verificação de duplicatas com um sistema de gamificação, criando um ambiente mais estruturado e motivador para os contribuidores. A implementação de feedback em tempo real e a adição de elementos lúdicos podem aumentar o engajamento da comunidade e melhorar a qualidade das contribuições.

**Descreva as alternativas que você considerou**
Verificação Manual de Duplicatas: Ineficiente e propensa a erros, especialmente em repositórios ativos.

**Uso de Labels:** Dependente da colaboração da comunidade, sem garantir detecção consistente.

**Bots de Moderação:** Alertam sobre duplicatas, mas não incluem gamificação, reduzindo o engajamento.

**Templates de Issue:** Ajudam a estruturar as sugestões, mas não resolvem a detecção automatizada de duplicatas.

**Gamificação Simples:** Oferece pontos por reportar issues, mas não incentiva diretamente a evitar duplicatas.

**Decisão Final**
A escolha pela Implementação de GitHub Action para verificar Issues duplicadas de forma gamificada combina automação com gamificação, promovendo contribuições conscientes e reduzindo duplicatas.

**Contexto adicional**
![issues duplicadas](https://github.com/user-attachments/assets/387db7cb-6066-4abb-9b10-5501514fff77)
Muitas pessoas têm criado issues semelhantes, copiando os exemplos fornecidos pela professora Elidiana. Isso tem gerado uma grande quantidade de duplicatas, poluindo o campo de issues e dificultando a identificação de solicitações e problemas relevantes.
